### ISSUE TITLE
Discussion and wiki

### ISSUE THREAD

**Issue by ameya0598** [Nsemble-Hope/Backend-API#1]
I think it will be good if some repos have discussion tab and the wiki tab opened, so that it is easy to communicate

**Comment by ameya0598** [comment]
Also adding figures from diagrams.net and related sites detailing api and architecture design would also be good.

**Comment by AtharvaSune** [comment]
Yep, working on it, first I need to figure out how to open discussion tab, wiki tab is there already I will look at it .

**Comment by AtharvaSune** [comment]
Not able to setup discussion, a features tab must be present in the settings page, but not there. :confused: 

@ameya0598

**Comment by AtharvaSune** [comment]
Got it discussions tab online
